apiVersion: backstage.io/v1alpha1
kind: Dbroadmap
metadata:
  name: zamboosh-authentication-users-db
  description: Authentication users db
schemas:
  - user:
    - id: [integer, index, incremental, unique]
    - full_name: [datatype, index]
    - hash_password: [string]
  - session:
    - timestamp: [date]
    - authorized: [boolean, defalte:false]
    - user_id: [integer]
spec:
  db_type: sql
  lifecycle: prod
  owner: team-a
  port: 3036
  user_permissions:
    - example-website: curdx
